### ISSUE TITLE
do problemheaderdetails ajnd problemheader really need to be PARAM_RAW ?

### ISSUE THREAD

**Issue by danmarsden** [marcusgreen/moodle-local_qbehaviour_interactiveexplain#2]
I can't see a reason why they couldn't just be PARAM_TEXT instead?

**Comment by marcusgreen** [comment]
I had not thought through the logic of using PARAM_RAW, but you have made me think about it now.

This is the string that is shown to people as part of the instructions to give feedback.
I assume that  if it is PARAM_TEXT it would not be possible to add URL's. It is unlikely that people would want to add URL's here, but they might want to do something like "for complete details on what you can say see this website http://www.howtoexplain.org.

As this should only be accessible to admins, it seems a reasonable thing to allow, or is there another PARAM_XXX I should use that does some filtering but not the laxity of PARAM_RAW. What do you think?

**Comment by danmarsden** [comment]
yeah - it's normally one of the things I'll do a quick code search for when reviewing code - searching for raw use of $_GET/$_POST etc.  It's not a blocker due to the location of the setting (admin user only) - feel free to close. :-)

**Comment by marcusgreen** [comment]
Thanks Dan
